### ISSUE TITLE
Clang not installed when selecting version 14

### ISSUE THREAD

**Issue by KungFuDonkey** [shenxianpeng/cpp-linter-action#51] opened 2022-04-15 21:42 UTC
This issur is related to [this](https://github.com/shenxianpeng/cpp-linter-action/discussions/50) discussion. If you select clang version 14, clang is not be installed correctly on the workflow, which can cause unexpected errors like system header files that are missing.

**Comment by 2bndy5** [comment] 2022-04-16 02:05
Reading the workflow's log that you linked in the discussion, it looks like clang-tidy-14 was able to be called and returned a result. Even if that result is undesirable, the fact that the clang-tidy-14 executable was found (& invoked) tells me that it isn't an installation problem. 

Have you tried using a compilation database (highly recommended)? This is a rather strict sticking point for clang-tidy (despite the version used).

**Comment by shenxianpeng** [comment] 2022-04-16 15:26
I have updated the docker image [`clang-tools:all`](https://hub.docker.com/layers/clang-tools/xianpengshen/clang-tools/all/images/sha256-0581d4b7f6e79b6d230192b68e76f5af7e4890d7ce370d108544c01075c9521a?context=explore) and I can not reproduce this issue anymore.

Currently, this is a temporary solution: just copy the missing *.h files to `/usr/include`, because keeping llvm-13 and llvm-14 folders in the image will extremely increase the size of the image and cause action to slow down.

**Comment by 2bndy5** [comment] 2022-04-16 15:34
> keeping llvm-13 and llvm-14 folders in the image will extremely increase the size of the image and cause action to slow down.

This is why I've been trying to use the action's src code as an installable python package. The docker image isn't needed if executing the action as a python package, but it does require the end-user to consciously install the desired version of clang-tidy & clang-format. Clearly, this will also require some finesse with the `--version` arg though.

**Comment by shenxianpeng** [comment] 2022-04-17 16:45
> Currently, this is a temporary solution: just copy the missing *.h files to /usr/include

UPDATE: Permanent solution has been done and the docker image has been updated. See https://github.com/shenxianpeng/clang-tools/issues/25

**Comment by shenxianpeng** [comment] 2022-04-18 16:17
This issue has been fixed in the latest docker image `xianpengshen/clang-tools:all`, I'm going to close it.
Please feel free to reopen it in case of any problems.

**Closed by shenxianpeng** 2022-04-18 16:17 UTC
